#!/usr/bin/env python3
"""One-click hardware optimisation for AI Studio.

Detects this machine's accelerator + memory, asks the recommendation engine for
the best settings, and writes a tuned ``backend/.env``. Safe to re-run anytime
(after a GPU upgrade, a driver change, etc.).

    python scripts/optimize.py            # detect, write backend/.env, print summary
    python scripts/optimize.py --print    # show what it would do, write nothing

It degrades gracefully: with no GPU (or torch not yet installed) it produces a
sensible CPU profile instead of failing.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
ENV_PATH = BACKEND / ".env"

# Make the backend package importable when run from anywhere.
sys.path.insert(0, str(BACKEND))


def _human_gb(mb: int) -> str:
    return f"{mb / 1024:.1f} GB" if mb else "n/a"


def build_env(rec, hw) -> dict:
    """Translate a RecommendationSet into concrete .env settings."""
    ig = rec.image_gen
    is_cpu = rec.backend == "cpu"
    budget = rec.vram_mb or int(hw.ram_total_mb * 0.7)

    # Megapixel cap with ~10% headroom over the recommended max resolution.
    w, h = ig.max_resolution
    megapixels = round((w * h) / 1_000_000 * 1.1, 2)

    env = {
        "DEBUG": "false",
        # Empty = autodetect the best device every run; we only pin to CPU when
        # there is genuinely no accelerator, to avoid surprising fallbacks.
        "DEVICE_PREFERENCE": "cpu" if is_cpu else "",
        "ENABLE_TORCH_COMPILE": str(ig.enable_torch_compile).lower(),
        # Live previews are great on a GPU but cripple CPU/low-VRAM runs.
        "ENABLE_LIVE_PREVIEW": "false" if is_cpu else "true",
        # Keep one pipeline resident on smaller cards; allow two when there's room.
        "MAX_PIPELINES_LOADED": "2" if budget >= 16384 else "1",
        "MAX_IMAGE_MEGAPIXELS": str(megapixels),
        "OLLAMA_BASE_URL": "http://localhost:11434",
    }
    return env


def write_env(env: dict, path: Path, tier: str) -> None:
    lines = [
        "# AI Studio — auto-generated by scripts/optimize.py",
        f"# Detected tier: {tier}",
        "# Re-run `python scripts/optimize.py` after a hardware/driver change.",
        "# Add HUGGINGFACE_TOKEN=hf_xxx below to use gated models (FLUX.1-dev, SD3.5).",
        "",
    ]
    lines += [f"{k}={v}" for k, v in env.items()]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Optimise AI Studio for this machine.")
    parser.add_argument("--print", dest="dry", action="store_true",
                        help="Show the recommended settings without writing .env")
    args = parser.parse_args()

    try:
        from hardware.detector import detect_hardware
        from hardware.recommender import recommend
    except Exception as exc:  # pragma: no cover
        print(f"!! Could not import the detection engine: {exc}")
        print("   Make sure backend dependencies are installed (run the installer).")
        return 1

    hw = detect_hardware(force_refresh=True)
    rec = recommend(hw)
    env = build_env(rec, hw)

    gpu = hw.primary_gpu
    print("\n=== AI Studio — hardware optimisation ===")
    print(f"  Accelerator : {rec.backend.upper()}"
          + (f" · {gpu.name}" if gpu else " (no GPU detected)"))
    print(f"  VRAM        : {_human_gb(rec.vram_mb)}"
          + ("  (reported by driver)" if rec.vram_mb else ""))
    print(f"  System RAM  : {_human_gb(hw.ram_total_mb)}")
    print(f"  Tier        : {rec.tier_label}")
    print("  ---")
    print(f"  Image models: {', '.join(rec.image_gen.recommended_models)}")
    print(f"  Max res     : {rec.image_gen.max_resolution[0]}x{rec.image_gen.max_resolution[1]}"
          f" · {rec.image_gen.recommended_steps} steps · {rec.image_gen.compute_dtype}")
    print(f"  LLM models  : {', '.join(rec.agent.recommended_models)}  (Ollama, {rec.agent.quantization})")
    print(f"  Train batch : {rec.training.recommended_batch_size}"
          f" · {rec.training.use_mixed_precision} · compile={rec.training.enable_torch_compile}")
    print("  ---")
    print("  .env settings:")
    for k, v in env.items():
        print(f"    {k}={v}")

    if args.dry:
        print("\n(--print) Nothing written.")
        return 0

    write_env(env, ENV_PATH, rec.tier_label)
    print(f"\n  Wrote {ENV_PATH.relative_to(ROOT)}")
    if rec.backend == "cpu":
        print("  Note: no GPU detected — image generation will be slow but functional.")
    print("  Done. Start the app with ./start.sh (or start.bat on Windows).\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
