"""initial schema

Revision ID: a1274da2193a
Revises: 
Create Date: 2026-06-17 18:47:15.484579
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1274da2193a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source', sa.Enum('huggingface', 'kaggle', 'upload', name='dataset_source'), nullable=False),
    sa.Column('source_identifier', sa.String(length=512), nullable=True),
    sa.Column('task_type', sa.Enum('classification', 'detection', 'segmentation', 'generation', 'nlp', name='task_type'), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('num_classes', sa.Integer(), nullable=False),
    sa.Column('class_names', sa.JSON(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('downloading', 'ready', 'error', name='dataset_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diffusion_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('repo_id', sa.String(length=512), nullable=False),
    sa.Column('pipeline_class', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('downloading', 'ready', 'error', name='diffusion_model_status'), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('min_vram_mb', sa.Integer(), nullable=False),
    sa.Column('recommended_steps', sa.Integer(), nullable=False),
    sa.Column('default_cfg', sa.Float(), nullable=False),
    sa.Column('default_width', sa.Integer(), nullable=False),
    sa.Column('default_height', sa.Integer(), nullable=False),
    sa.Column('supports_negative_prompt', sa.Boolean(), nullable=False),
    sa.Column('gated', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diffusion_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diffusion_models_repo_id'), ['repo_id'], unique=True)

    op.create_table('image_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('model_id', sa.String(length=256), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('cfg_scale', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('sampler', sa.String(length=64), nullable=False),
    sa.Column('num_images', sa.Integer(), nullable=False),
    sa.Column('output_paths', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'paused', 'completed', 'failed', 'cancelled', name='run_status'), nullable=False),
    sa.Column('architecture', sa.String(length=64), nullable=False),
    sa.Column('arch_config', sa.JSON(), nullable=False),
    sa.Column('training_config', sa.JSON(), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('hardware_snapshot', sa.JSON(), nullable=True),
    sa.Column('metrics_history', sa.JSON(), nullable=False),
    sa.Column('best_checkpoint_path', sa.Text(), nullable=True),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('total_epochs', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_runs')
    op.drop_table('image_jobs')
    with op.batch_alter_table('diffusion_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diffusion_models_repo_id'))

    op.drop_table('diffusion_models')
    op.drop_table('datasets')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
